#!/bin/bash

conky -c /usr/share/conky/conky1.10_shortcuts_maia &&
conky -c /usr/share/conky/conky1.20_vim_maia &&
conky -c /usr/share/conky/conky1.30_qutebrowser_maia &&
#conky -c /usr/share/conky/conky_maia &&
conky -c /usr/share/conky/conky2_maia &&

exit 0
